### PR TITLE
Set up react, and redux toolkit fetching from an api

### PR DESCRIPTION
**Pull request by alphayowakarindi**
At this juncture of development, I implemented the following:
 - Set up fresh rails app with Postgres database, react, webpack and redux toolkit
 - Create a table for storing messages and create 5 different greetings. 
 - Create an API endpoint that selects a random greeting from the table
 - Create a static view that will be the root of the app.
- Create the `App` component with react-router and render it in the static view.
- Create the `Greeting` component that will display a greeting. Set it up as a route in the App component.
- Create a store, an action, and a reducer that connects to the API endpoint to get the random greeting.
- Display the random greeting in the `Greeting` component.

### CODE REVIEW

**Review by andersonlebon — APPROVED** [review]
## Hi @alphayowakarindi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alphayowakarindi** [comment]
Hi @andersonlebon, thank you so much for taking the time to leave this excellent review. Cheers!

**Comment by andersonlebon** [comment]
thanks, @alphayowakarindi, would you kindly please check the status of this project on your dashboard?

**Comment by alphayowakarindi** [comment]
@andersonlebon I submitted it and it shows completed.

**Pull request merged**
